# -*- coding: utf-8 -*-
"""MulticlassClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_gXxBh2Sh004aa9NCFEzbz4YpPlBgk7
"""

from google.colab import drive
drive.mount('/content/drive')

!nvdia-smi





!wget https://bitbucket.org/ishaanjav/code-and-deploy-custom-tensorflow-lite-model/raw/a4febbfee178324b2083e322cdead7465d6fdf95/fruits.zip

!unzip fruits.zip

import tensorflow as tf
import matplotlib.pyplot as plt

img_height, img_width = 32, 32
batch_size = 20

train_ds = tf.keras.utils.image_dataset_from_directory(
    "fruits/train",
    image_size = (img_height, img_width),
    batch_size = batch_size
)
val_ds = tf.keras.utils.image_dataset_from_directory(
    "fruits/validation",
    image_size = (img_height, img_width),
    batch_size = batch_size
)
test_ds = tf.keras.utils.image_dataset_from_directory(
    "fruits/test",
    image_size = (img_height, img_width),
    batch_size = batch_size
)

class_names = ["apple","banana","orange"]
plt.figure(figsize=(10, 10))
for images, labels in train_ds.take(1):
  for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(images[i].numpy().astype("uint8"))
    plt.title(class_names[labels[i]])
    plt.axis("off")

model = tf.keras.Sequential(
    [
    tf.keras.layers.Rescaling(1./255),
    tf.keras.layers.Conv2D(32, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(64, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(128, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='softmax'),
    tf.keras.layers.Dense(3)

    ])

model.compile(
    optimizer='rmsprop',
    loss=tf.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy'])

model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20
)

import numpy

plt.figure(figsize=(10, 10))

for images, labels in test_ds.take(1):
  classification = model.predict(images)

for i in range(9):
  ax = plt.subplot(3, 3, i +1)
  plt.imshow(images[i].numpy().astype("uint8"))
  index= numpy.argmax(classification[i])
  plt.title("pred: "+class_names[index]+", act: "+class_names[labels[i]])